server:
  port: 8080
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/todos
    #username: root
    #password:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:file:./todos
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
